name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build Tools
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.2"

      - name: Build APK
        uses: digreatbrian/buildozer-action@v1
        with:
          workdir: .
          buildozer-cmd: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
