name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Install Android Build Tools
        run: |
          sdkmanager --install "platform-tools"
          sdkmanager --install "platforms;android-33"
          sdkmanager --install "build-tools;33.0.2"
          sdkmanager --install "build-tools;37.0.0"

      - name: Verify AIDL
        run: |
          find $ANDROID_SDK_ROOT -name aidl || true

      - name: Build APK
        uses: digreatbrian/buildozer-action@v1
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        with:
          workdir: .
          buildozer-cmd: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
